# Generated by Django 2.0.5 on 2018-05-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
