backend:
  name: git-gateway
  branch: master
media_folder: "/files/assets/img"
public_folder: "/assets/img"
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Titre", name: "layout", widget: "hidden", default: ""}
      - {label: "Slug", name: "layout", widget: "hidden", default: ""}
      - {label: "Date", name: "layout", widget: "hidden", default: ""}
      - {label: "Etiquettes", name: "layout", widget: "hidden", default: ""}
      - {label: "Catégorie", name: "layout", widget: "hidden", default: ""}
      - {label: "Descriptionn", name: "layout", widget: "hidden", default: ""}
      - {label: "Type", name: "layout", widget: "hidden", default: "text"}
