name: Build website with Nikola

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        $HOME/.poetry/bin/poetry install
    - name: Update submodules
      run: |
        git submodule init
        git submodule update
    - name: Build website
      run: $HOME/.poetry/bin/poetry run nikola build
